# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 31bf455fc4af5dab7e225edbc7a1d51af4d9a81e0c5756fb53baeab3e53c9908f215929e1007c07c4d9f277f61d8b74ab6fabc8d3c52b81cdaa6cad096a9ab67

test:
  secret_key_base: a237c4c9c1d9ce2237ad2be8f55ef9f740a9d93046ed2e0b46d150384d5c36afe1d1162aa05b7b27678feda51c777fdcb7ec2ca6feebd227d369cfd87ef5c46d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
